/datum/asset/simple/heretic_book
	assets = list(
		"heretic-ash.webp" = 'tgui/packages/tgui/assets/heretic-ash.webp',
		"heretic-rust.webp" = 'tgui/packages/tgui/assets/heretic-rust.webp',
		"heretic-flesh.webp" = 'tgui/packages/tgui/assets/heretic-flesh.webp',
		"heretic-void.webp" = 'tgui/packages/tgui/assets/heretic-void.webp',
		"heretic-blade.webp" = 'tgui/packages/tgui/assets/heretic-blade.webp',
		"heretic-moon.webp" = 'tgui/packages/tgui/assets/heretic-moon.webp',
		"heretic-cosmic.webp" = 'tgui/packages/tgui/assets/heretic-cosmic.webp',
		"heretic-lock.webp" = 'tgui/packages/tgui/assets/heretic-lock.webp',
		"heretic-tide.webp" = 'tgui/packages/tgui/assets/heretic-tide.webp',
		"heretic-glass.webp" = 'tgui/packages/tgui/assets/heretic-glass.webp',
		"heretic-blood.webp" = 'tgui/packages/tgui/assets/heretic-blood.webp',
	)

/proc/heretic_ritual_ingredient_name(atom/ingredient_type)
	var/static/list/names = list(
		/mob/living/carbon/human = "Человеческий труп",
		/obj/effect/decal/cleanable/ash = "Пепел",
		/obj/effect/decal/cleanable/blood = "Лужа крови",
		/obj/effect/decal/cleanable/vomit = "Рвота",
		/obj/item/bedsheet = "Простыня",
		/obj/item/bodypart/head = "Отрубленная голова",
		/obj/item/bodypart/l_arm = "Левая рука",
		/obj/item/bodypart/l_leg = "Левая нога",
		/obj/item/bodypart/r_arm = "Правая рука",
		/obj/item/bodypart/r_leg = "Правая нога",
		/obj/item/book = "Книга",
		/obj/item/candle = "Свеча",
		/obj/item/crowbar = "Лом",
		/obj/item/clothing/mask = "Маска",
		/obj/item/clothing/mask/gas = "Противогаз",
		/obj/item/clothing/suit = "Верхняя одежда",
		/obj/item/flashlight/lantern = "Фонарь",
		/obj/item/hatchet = "Топорик",
		/obj/item/hemostat = "Хирургический зажим",
		/obj/item/kitchen/fork = "Вилка",
		/obj/item/kitchen/knife = "Кухонный нож",
		/obj/item/lighter = "Зажигалка",
		/obj/item/living_heart = "Живое сердце",
		/obj/item/match = "Спичка",
		/obj/item/organ = "Извлечённый орган",
		/obj/item/organ/eyes = "Глаза",
		/obj/item/organ/heart = "Сердце",
		/obj/item/paper = "Лист бумаги",
		/obj/item/pen = "Ручка",
		/obj/item/reagent_containers/food/drinks/drinkingglass = "Стеклянный стакан",
		/obj/item/reagent_containers/food/snacks/grown/poppy = "Мак",
		/obj/item/reagent_containers/glass/beaker = "Мензурка",
		/obj/item/shard = "Осколок стекла",
		/obj/item/stack/cable_coil = "Кабель",
		/obj/item/stack/medical/suture = "Шовная нить",
		/obj/item/stack/rods = "Металлический стержень",
		/obj/item/stack/sheet/animalhide/human = "Человеческая кожа",
		/obj/item/stack/sheet/glass = "Лист стекла",
		/obj/item/stack/sheet/metal = "Лист железа",
		/obj/item/stack/sheet/mineral/gold = "Слиток золота",
		/obj/item/stack/sheet/mineral/silver = "Слиток серебра",
		/obj/item/storage/book/bible = "Библия",
		/obj/item/trash = "Мусор",
		/obj/item/wirecutters = "Кусачки",
		/obj/structure/reagent_dispensers/watertank = "Бак с водой",
		/obj/structure/table = "Стол",
	)
	return names[ingredient_type] || initial(ingredient_type.name)
