/* Bitmask icon smoothing system (ported from Bubberstation) */

#define SMOOTH_BITMASK (1<<0)
#define SMOOTH_BITMASK_CARDINALS (1<<1)
#define SMOOTH_DIAGONAL_CORNERS (1<<2)
#define SMOOTH_OBJ (1<<5)
#define SMOOTH_BORDER_OBJECT (1<<6)
#define SMOOTH_PROC_FILTER (1<<7)

#define USES_SMOOTHING (SMOOTH_BITMASK|SMOOTH_BITMASK_CARDINALS)

DEFINE_BITFIELD(smoothing_flags, list(
	"SMOOTH_BITMASK" = SMOOTH_BITMASK,
	"SMOOTH_BITMASK_CARDINALS" = SMOOTH_BITMASK_CARDINALS,
	"SMOOTH_DIAGONAL_CORNERS" = SMOOTH_DIAGONAL_CORNERS,
	"SMOOTH_OBJ" = SMOOTH_OBJ,
	"SMOOTH_BORDER_OBJECT" = SMOOTH_BORDER_OBJECT,
	"SMOOTH_PROC_FILTER" = SMOOTH_PROC_FILTER,
))

#define NORTH_JUNCTION NORTH
#define SOUTH_JUNCTION SOUTH
#define EAST_JUNCTION EAST
#define WEST_JUNCTION WEST
#define NORTHEAST_JUNCTION (1<<4)
#define SOUTHEAST_JUNCTION (1<<5)
#define SOUTHWEST_JUNCTION (1<<6)
#define NORTHWEST_JUNCTION (1<<7)

#define CARDINAL_SMOOTHING_JUNCTIONS (NORTH_JUNCTION|SOUTH_JUNCTION|EAST_JUNCTION|WEST_JUNCTION)
#define ALL_SMOOTHING_JUNCTIONS (NORTH_JUNCTION|SOUTH_JUNCTION|EAST_JUNCTION|WEST_JUNCTION|NORTHEAST_JUNCTION|SOUTHEAST_JUNCTION|SOUTHWEST_JUNCTION|NORTHWEST_JUNCTION)

DEFINE_BITFIELD(smoothing_junction, list(
	"NORTH_JUNCTION" = NORTH_JUNCTION,
	"SOUTH_JUNCTION" = SOUTH_JUNCTION,
	"EAST_JUNCTION" = EAST_JUNCTION,
	"WEST_JUNCTION" = WEST_JUNCTION,
	"NORTHEAST_JUNCTION" = NORTHEAST_JUNCTION,
	"SOUTHEAST_JUNCTION" = SOUTHEAST_JUNCTION,
	"SOUTHWEST_JUNCTION" = SOUTHWEST_JUNCTION,
	"NORTHWEST_JUNCTION" = NORTHWEST_JUNCTION,
))

#define QUEUE_SMOOTH(thing_to_queue) if(thing_to_queue.smoothing_flags & USES_SMOOTHING) {SSicon_smooth.add_to_queue(thing_to_queue)}

#define QUEUE_SMOOTH_NEIGHBORS(thing_to_queue) for(var/atom/atom_neighbor as anything in orange(1, thing_to_queue)) {QUEUE_SMOOTH(atom_neighbor)}

#define S_TURF(num) (#num + ",")

#define SMOOTH_GROUP_CLOSED_TURFS S_TURF(57)
#define SMOOTH_GROUP_MATERIAL_WALLS S_TURF(58)
#define SMOOTH_GROUP_SYNDICATE_WALLS S_TURF(59)
#define SMOOTH_GROUP_MINERAL_WALLS S_TURF(61)
#define SMOOTH_GROUP_SURVIVAL_TITANIUM_WALLS S_TURF(65)
#define SMOOTH_GROUP_PLASTINUM_WALLS S_TURF(68)

#define MAX_S_TURF 73

#define S_OBJ(num) ("-" + #num + ",")

#define SMOOTH_GROUP_WALLS S_OBJ(1)
#define SMOOTH_GROUP_URANIUM_WALLS S_OBJ(2)
#define SMOOTH_GROUP_GOLD_WALLS S_OBJ(3)
#define SMOOTH_GROUP_SILVER_WALLS S_OBJ(4)
#define SMOOTH_GROUP_DIAMOND_WALLS S_OBJ(5)
#define SMOOTH_GROUP_PLASMA_WALLS S_OBJ(6)
#define SMOOTH_GROUP_BANANIUM_WALLS S_OBJ(7)
#define SMOOTH_GROUP_SANDSTONE_WALLS S_OBJ(8)
#define SMOOTH_GROUP_WOOD_WALLS S_OBJ(9)
#define SMOOTH_GROUP_IRON_WALLS S_OBJ(10)
#define SMOOTH_GROUP_ABDUCTOR_WALLS S_OBJ(11)
#define SMOOTH_GROUP_TITANIUM_WALLS S_OBJ(12)
#define SMOOTH_GROUP_PLASTITANIUM_WALLS S_OBJ(14)
#define SMOOTH_GROUP_SURVIVAL_TITANIUM_POD S_OBJ(15)
#define SMOOTH_GROUP_BAMBOO_WALLS S_OBJ(17)
#define SMOOTH_GROUP_WINDOW_FULLTILE S_OBJ(22)
#define SMOOTH_GROUP_WINDOW_FULLTILE_BRONZE S_OBJ(23)
#define SMOOTH_GROUP_WINDOW_FULLTILE_PLASTITANIUM S_OBJ(24)
#define SMOOTH_GROUP_WINDOW_FULLTILE_SHUTTLE S_OBJ(25)
#define SMOOTH_GROUP_AIRLOCK S_OBJ(41)
#define SMOOTH_GROUP_SHUTTLE_PARTS S_OBJ(67)
#define SMOOTH_GROUP_GIRDER S_OBJ(76)
#define SMOOTH_GROUP_SNOW_WALLS S_OBJ(92)
#define SMOOTH_GROUP_CLOCKWORK_WALLS S_OBJ(93)
#define SMOOTH_GROUP_CULT_WALLS S_OBJ(94)
#define SMOOTH_GROUP_NECROPOLIS_WALLS S_OBJ(95)
#define SMOOTH_GROUP_BRONZE_TABLES S_OBJ(54)

#define SETUP_SMOOTHING(...) \
	if (istext(smoothing_groups)) { \
		PARSE_SMOOTHING_GROUPS(smoothing_groups, smoothing_groups); \
	} \
	if (smoothing_flags & USES_SMOOTHING) { \
		if (canSmoothWith) { \
			PARSE_CAN_SMOOTH_WITH(canSmoothWith, canSmoothWith, smoothing_flags); \
		} \
	}

#define PARSE_SMOOTHING_GROUPS(parse_from, set_into) \
	SET_SMOOTHING_GROUPS(parse_from, set_into);

#define PARSE_CAN_SMOOTH_WITH(parse_from, set_into, set_flags_into) \
	if (istext(parse_from)) { \
		if (parse_from[1] == "-") { \
			set_flags_into |= SMOOTH_OBJ; \
		} \
		SET_SMOOTHING_GROUPS(parse_from, set_into); \
	}

#define UNWRAP_SMOOTHING_GROUPS(smoothing_groups, out) \
	json_decode("\[[##smoothing_groups]0\]"); \
	##out.len--;
