#define CYBERPSYCHOSIS_TIER_NONE     0
#define CYBERPSYCHOSIS_TIER_MILD     1
#define CYBERPSYCHOSIS_TIER_MODERATE 2
#define CYBERPSYCHOSIS_TIER_CRITICAL 3

#define CYBERPSYCHOSIS_MILD_LOAD     8
#define CYBERPSYCHOSIS_MODERATE_LOAD 15
#define CYBERPSYCHOSIS_CRITICAL_LOAD 20

#define CYBERPSYCHOSIS_MILD_COMPATIBLE_OFFSET     4
#define CYBERPSYCHOSIS_MODERATE_COMPATIBLE_OFFSET 5
#define CYBERPSYCHOSIS_CRITICAL_COMPATIBLE_OFFSET 7

#define TRAIT_IMPLANT_COMPATIBILITY "implant_compatibility"

#define CYBERPSYCHOSIS_OTHER_VIEW_RANGE 7

#define CYBERPSYCHOSIS_CRITICAL_FILTER list(type = "drop_shadow", x = 0, y = 0, size = -4, color = "#07070B")

#define CYBERPSYCHOSIS_EMP_OVERLOAD_PER_IMPLANT 0.5
#define CYBERPSYCHOSIS_EMP_OVERLOAD_DECAY_TIME 60