#define ANTAG_TRAINING_SIZE 55
#define ANTAG_TRAINING_MAX_ARENAS 1
#define ANTAG_TRAINING_DISCONNECT_GRACE (1 MINUTES)
#define ANTAG_TRAINING_TARGET_LIMIT 12
#define ANTAG_TRAINING_SUPPLY_LIMIT 100
#define ANTAG_TRAINING_WORK_BUDGET_MS 5
#define ANTAG_TRAINING_RESTART_DELAY (5 SECONDS)
#define ANTAG_TRAINING_VOTE_TIME (45 SECONDS)
