/datum/unit_test/cyberpsychosis_subdermal_implants_no_load/Run()
	var/mob/living/carbon/human/H = allocate(/mob/living/carbon/human)
	var/obj/item/implant/mindshield/MS = new /obj/item/implant/mindshield()
	MS.implant(H, null, TRUE)
	var/obj/item/implant/warp/W = new /obj/item/implant/warp()
	W.implant(H, null, TRUE)
	var/obj/item/implant/adrenalin/AD = new /obj/item/implant/adrenalin()
	AD.implant(H, null, TRUE)
	H.update_cyberpsychosis()
	TEST_ASSERT_NULL(H.cyberpsychosis, "Подкожные импланты создали киберпсихоз")

/datum/unit_test/cyberpsychosis_cyberimp_default_load/Run()
	var/obj/item/organ/cyberimp/CO = new /obj/item/organ/cyberimp()
	TEST_ASSERT_EQUAL(CO.cyber_load, 1, "Базовый /obj/item/organ/cyberimp должен иметь cyber_load = 1, получено [CO.cyber_load]")
	qdel(CO)

/datum/unit_test/cyberpsychosis_no_cyberimps_no_datum/Run()
	var/mob/living/carbon/human/H = allocate(/mob/living/carbon/human)
	H.update_cyberpsychosis()
	TEST_ASSERT_NULL(H.cyberpsychosis, "Датum киберпсихоза создался без кибераугментов")

/datum/unit_test/cyberpsychosis_load_by_purpose/Run()
	var/obj/item/organ/cyberimp/brain/anti_stun/br = new /obj/item/organ/cyberimp/brain/anti_stun()
	TEST_ASSERT_EQUAL(br.cyber_load, 1, "anti-stun: cyber_load=[br.cyber_load], ожидался 1")
	qdel(br)
	var/obj/item/organ/cyberimp/eyes/hud/medical/hud = new /obj/item/organ/cyberimp/eyes/hud/medical()
	TEST_ASSERT_EQUAL(hud.cyber_load, 1, "medical HUD: cyber_load=[hud.cyber_load], ожидался 1")
	qdel(hud)
	var/obj/item/organ/cyberimp/arm/toolset/ts = new /obj/item/organ/cyberimp/arm/toolset()
	TEST_ASSERT_EQUAL(ts.cyber_load, 1, "toolset: cyber_load=[ts.cyber_load], ожидался 1")
	qdel(ts)
	var/obj/item/organ/cyberimp/arm/surgery/surg = new /obj/item/organ/cyberimp/arm/surgery()
	TEST_ASSERT_EQUAL(surg.cyber_load, 2, "surgery: cyber_load=[surg.cyber_load], ожидался 2")
	qdel(surg)
	var/obj/item/organ/cyberimp/chest/reviver/rv = new /obj/item/organ/cyberimp/chest/reviver()
	TEST_ASSERT_EQUAL(rv.cyber_load, 2, "reviver: cyber_load=[rv.cyber_load], ожидался 2")
	qdel(rv)
	var/obj/item/organ/cyberimp/chest/thrusters/th = new /obj/item/organ/cyberimp/chest/thrusters()
	TEST_ASSERT_EQUAL(th.cyber_load, 2, "thrusters: cyber_load=[th.cyber_load], ожидался 2")
	qdel(th)
	var/obj/item/organ/cyberimp/arm/gun/laser/las = new /obj/item/organ/cyberimp/arm/gun/laser()
	TEST_ASSERT_EQUAL(las.cyber_load, 3, "arm laser: cyber_load=[las.cyber_load], ожидался 3")
	qdel(las)
	var/obj/item/organ/cyberimp/arm/combat/cb = new /obj/item/organ/cyberimp/arm/combat()
	TEST_ASSERT_EQUAL(cb.cyber_load, 3, "combat arm: cyber_load=[cb.cyber_load], ожидался 3")
	qdel(cb)
	var/obj/item/organ/cyberimp/chest/chem_implant/ch = new /obj/item/organ/cyberimp/chest/chem_implant()
	TEST_ASSERT_EQUAL(ch.cyber_load, 3, "chem implant: cyber_load=[ch.cyber_load], ожидался 3")
	qdel(ch)

	var/mob/living/carbon/human/H = allocate(/mob/living/carbon/human)
	var/obj/item/organ/cyberimp/arm/gun/laser/gun = new /obj/item/organ/cyberimp/arm/gun/laser()
	gun.Insert(H)
	var/obj/item/organ/cyberimp/eyes/hud/medical/hud2 = new /obj/item/organ/cyberimp/eyes/hud/medical()
	hud2.Insert(H)
	var/obj/item/organ/cyberimp/mouth/breathing_tube/mouth = new /obj/item/organ/cyberimp/mouth/breathing_tube()
	mouth.Insert(H)
	var/obj/item/organ/cyberimp/brain/anti_stun/brain = new /obj/item/organ/cyberimp/brain/anti_stun()
	brain.Insert(H)
	var/obj/item/organ/cyberimp/arm/surgery/surg2 = new /obj/item/organ/cyberimp/arm/surgery()
	surg2.Insert(H)
	H.update_cyberpsychosis(FALSE)
	TEST_ASSERT_NOTNULL(H.cyberpsychosis, "Датum не создался при установке кибераугментов")
	TEST_ASSERT_EQUAL(H.cyberpsychosis.load, 8, "load=[H.cyberpsychosis.load], ожидался 8 (3+1+1+1+2)")
	TEST_ASSERT_EQUAL(H.cyberpsychosis.stage, CYBERPSYCHOSIS_TIER_MILD, "load=8 не дал MILD")
	gun.Remove(FALSE)
	qdel(gun)
	H.update_cyberpsychosis(FALSE)
	TEST_ASSERT_EQUAL(H.cyberpsychosis.load, 5, "load=[H.cyberpsychosis.load] после снятия, ожидался 5")
	TEST_ASSERT_EQUAL(H.cyberpsychosis.stage, CYBERPSYCHOSIS_TIER_NONE, "load=5 не дал NONE")
	qdel(H.cyberpsychosis)

/datum/unit_test/cyberpsychosis_stage_thresholds/Run()
	var/mob/living/carbon/human/H = allocate(/mob/living/carbon/human)
	var/datum/cyberpsychosis/CP = new /datum/cyberpsychosis(H)
	CP.update_stage(FALSE, 0)
	TEST_ASSERT_EQUAL(CP.stage, CYBERPSYCHOSIS_TIER_NONE, "load=0 должен быть NONE")
	CP.update_stage(FALSE, 7)
	TEST_ASSERT_EQUAL(CP.stage, CYBERPSYCHOSIS_TIER_NONE, "load=7 должен быть NONE (MILD с 8)")
	CP.update_stage(FALSE, 8)
	TEST_ASSERT_EQUAL(CP.stage, CYBERPSYCHOSIS_TIER_MILD, "load=8 должен быть MILD")
	CP.update_stage(FALSE, 14)
	TEST_ASSERT_EQUAL(CP.stage, CYBERPSYCHOSIS_TIER_MILD, "load=14 должен быть MILD (MODERATE с 15)")
	CP.update_stage(FALSE, 15)
	TEST_ASSERT_EQUAL(CP.stage, CYBERPSYCHOSIS_TIER_MODERATE, "load=15 должен быть MODERATE")
	CP.update_stage(FALSE, 19)
	TEST_ASSERT_EQUAL(CP.stage, CYBERPSYCHOSIS_TIER_MODERATE, "load=19 должен быть MODERATE (CRITICAL с 20)")
	CP.update_stage(FALSE, 20)
	TEST_ASSERT_EQUAL(CP.stage, CYBERPSYCHOSIS_TIER_CRITICAL, "load=20 должен быть CRITICAL")
	TEST_ASSERT_NOTNULL(H.get_filter("cyberpsychosis"), "Фильтр критической стадии не применён")
	TEST_ASSERT(H.eye_blurry > 0, "Блюр экрана не применён на критической стадии")
	CP.update_stage(FALSE, 0)
	TEST_ASSERT_EQUAL(CP.stage, CYBERPSYCHOSIS_TIER_NONE, "Стадия не сбросилась при load=0")
	TEST_ASSERT_EQUAL(H.eye_blurry, 0, "Блюр экрана не был снят после падения стадии")
	TEST_ASSERT_NULL(H.get_filter("cyberpsychosis"), "Фильтр критической стадии не снят после падения стадии")
	qdel(CP)

/datum/unit_test/cyberpsychosis_threshold_offset_quirk/Run()
	var/mob/living/carbon/human/H = allocate(/mob/living/carbon/human)
	var/datum/cyberpsychosis/CP = new /datum/cyberpsychosis(H)
	CP.update_stage(FALSE, 19)
	TEST_ASSERT_EQUAL(CP.stage, CYBERPSYCHOSIS_TIER_MODERATE, "Без квирка load=19 должен быть MODERATE")
	ADD_TRAIT(H, TRAIT_IMPLANT_COMPATIBILITY, "unit_test")
	CP.update_stage(FALSE, 11)
	TEST_ASSERT_EQUAL(CP.stage, CYBERPSYCHOSIS_TIER_NONE, "С квирком load=11 должен быть NONE (MILD с 12)")
	CP.update_stage(FALSE, 12)
	TEST_ASSERT_EQUAL(CP.stage, CYBERPSYCHOSIS_TIER_MILD, "С квирком load=12 должен быть MILD")
	CP.update_stage(FALSE, 19)
	TEST_ASSERT_EQUAL(CP.stage, CYBERPSYCHOSIS_TIER_MILD, "С квирком load=19 должен быть MILD (MODERATE с 20)")
	CP.update_stage(FALSE, 20)
	TEST_ASSERT_EQUAL(CP.stage, CYBERPSYCHOSIS_TIER_MODERATE, "С квирком load=20 должен быть MODERATE")
	CP.update_stage(FALSE, 26)
	TEST_ASSERT_EQUAL(CP.stage, CYBERPSYCHOSIS_TIER_MODERATE, "С квирком load=26 должен быть MODERATE (CRITICAL с 27)")
	CP.update_stage(FALSE, 27)
	TEST_ASSERT_EQUAL(CP.stage, CYBERPSYCHOSIS_TIER_CRITICAL, "С квирком load=27 должен быть CRITICAL")
	REMOVE_TRAIT(H, TRAIT_IMPLANT_COMPATIBILITY, "unit_test")
	CP.update_stage(FALSE, 19)
	TEST_ASSERT_EQUAL(CP.stage, CYBERPSYCHOSIS_TIER_MODERATE, "После снятия квирка load=19 снова MODERATE")
	qdel(CP)

/datum/unit_test/cyberpsychosis_critical_filter_applied/Run()
	var/mob/living/carbon/human/H = allocate(/mob/living/carbon/human)
	var/datum/cyberpsychosis/CP = new /datum/cyberpsychosis(H)
	CP.update_stage(FALSE, CYBERPSYCHOSIS_CRITICAL_LOAD)
	TEST_ASSERT_EQUAL(CP.stage, CYBERPSYCHOSIS_TIER_CRITICAL, "load=20 не дал CRITICAL")
	TEST_ASSERT_NOTNULL(H.get_filter("cyberpsychosis"), "Фильтр критической стадии не применён")
	TEST_ASSERT(H.eye_blurry > 0, "Блюр экрана не применён на критической стадии")
	qdel(CP)

/datum/unit_test/cyberpsychosis_emp_overload/Run()
	var/mob/living/carbon/human/H = allocate(/mob/living/carbon/human)
	var/datum/cyberpsychosis/CP = new /datum/cyberpsychosis(H)
	CP.update_stage(FALSE, CYBERPSYCHOSIS_MODERATE_LOAD - 1)
	TEST_ASSERT_EQUAL(CP.stage, CYBERPSYCHOSIS_TIER_MILD, "load=14 должен быть MILD")
	TEST_ASSERT_EQUAL(CP.temp_overload, 0, "temp_overload до ЭМИ должен быть 0")
	CP.add_emp_overload(CYBERPSYCHOSIS_EMP_OVERLOAD_PER_IMPLANT)
	TEST_ASSERT_EQUAL(CP.stage, CYBERPSYCHOSIS_TIER_MILD, "load=14+0.5 должен остаться MILD")
	TEST_ASSERT(round(CP.temp_overload, 0.001) == CYBERPSYCHOSIS_EMP_OVERLOAD_PER_IMPLANT, "temp_overload=0.5 не накоплен")
	CP.add_emp_overload(CYBERPSYCHOSIS_EMP_OVERLOAD_PER_IMPLANT)
	TEST_ASSERT_EQUAL(CP.stage, CYBERPSYCHOSIS_TIER_MODERATE, "load=14+1.0 должен дать MODERATE")
	CP.decay_temp_overload(30)
	CP.update_stage(FALSE)
	TEST_ASSERT_EQUAL(CP.stage, CYBERPSYCHOSIS_TIER_MILD, "load=14+0.75 должен вернуться к MILD")
	CP.decay_temp_overload(90)
	CP.update_stage(FALSE)
	TEST_ASSERT(round(CP.temp_overload, 0.001) == 0, "temp_overload не спал до нуля")
	TEST_ASSERT_EQUAL(CP.stage, CYBERPSYCHOSIS_TIER_MILD, "После спада стадия не вернулась к MILD")
	CP.add_emp_overload(CYBERPSYCHOSIS_EMP_OVERLOAD_PER_IMPLANT * 6)
	TEST_ASSERT_EQUAL(CP.stage, CYBERPSYCHOSIS_TIER_CRITICAL, "load=14+3.0 должен дать CRITICAL")
	CP.clear_temp_overload()
	TEST_ASSERT_EQUAL(CP.temp_overload, 0, "Псикодин не сбросил temp_overload")
	TEST_ASSERT_EQUAL(CP.stage, CYBERPSYCHOSIS_TIER_MILD, "Псикодин не вернул стадию к MILD")
	TEST_ASSERT_NULL(H.get_filter("cyberpsychosis"), "Фильтр критической стадии не снят после псикодина")
	qdel(CP)

/datum/unit_test/cyberpsychosis_emp_act_stacks/Run()
	var/mob/living/carbon/human/H = allocate(/mob/living/carbon/human)
	var/obj/item/organ/cyberimp/arm/toolset/ts = new /obj/item/organ/cyberimp/arm/toolset()
	ts.Insert(H)
	var/obj/item/organ/cyberimp/eyes/hud/medical/hud = new /obj/item/organ/cyberimp/eyes/hud/medical()
	hud.Insert(H)
	var/obj/item/organ/cyberimp/mouth/breathing_tube/mouth = new /obj/item/organ/cyberimp/mouth/breathing_tube()
	mouth.Insert(H)
	TEST_ASSERT_NOTNULL(H.cyberpsychosis, "Датum не создался при установке кибераугментов")
	TEST_ASSERT_EQUAL(H.cyberpsychosis.load, 3, "load должен быть 3 (1+1+1)")
	TEST_ASSERT_EQUAL(H.cyberpsychosis.stage, CYBERPSYCHOSIS_TIER_NONE, "load=3 должен быть NONE")
	ts.emp_act(2)
	TEST_ASSERT(round(H.cyberpsychosis.temp_overload, 0.001) == 0.5, "temp_overload после ЭМИ по toolset != 0.5")
	hud.emp_act(2)
	TEST_ASSERT(round(H.cyberpsychosis.temp_overload, 0.001) == 1.0, "temp_overload после ЭМИ по HUD != 1.0")
	mouth.emp_act(2)
	TEST_ASSERT(round(H.cyberpsychosis.temp_overload, 0.001) == 1.5, "temp_overload после ЭМИ по breathing_tube != 1.5")
	TEST_ASSERT_EQUAL(H.cyberpsychosis.stage, CYBERPSYCHOSIS_TIER_NONE, "load=3+1.5 должен быть NONE")
	qdel(H.cyberpsychosis)