/// Фикстура регистрирует только владельца знаний: разломы, цели охоты и экипировка здесь не нужны.
/datum/unit_test/proc/make_moon_heretic(turf/location)
	var/mob/living/carbon/human/body = allocate(/mob/living/carbon/human, location)
	body.mind_initialize()
	var/datum/antagonist/heretic/heretic = allocate(/datum/antagonist/heretic)
	heretic.owner = body.mind
	heretic.role_removed = TRUE
	heretic.silent = TRUE
	LAZYADD(body.mind.antag_datums, heretic)
	var/datum/eldritch_knowledge/base_moon/knowledge = allocate(/datum/eldritch_knowledge/base_moon)
	heretic.researched_knowledge[knowledge.type] = knowledge
	knowledge.on_body_gain(body)
	return body

/datum/unit_test/heretic_moon_limits/Run()
	var/mob/living/user = make_moon_heretic(run_loc_floor_bottom_left)
	var/datum/eldritch_knowledge/base_moon/knowledge = get_heretic_moon(user)
	var/turf/first_turf = get_step(user, EAST)
	var/turf/second_turf = get_step(user, NORTH)
	var/turf/third_turf = get_step(user, NORTHEAST)
	var/mob/living/simple_animal/hostile/illusion/heretic_moon/first = knowledge.create_reflection(user, first_turf)
	var/mob/living/simple_animal/hostile/illusion/heretic_moon/second = knowledge.create_reflection(user, second_turf)
	TEST_ASSERT(first && second, "Два отражения должны создаваться на свободном полу.")
	TEST_ASSERT_NULL(knowledge.create_reflection(user, third_turf), "Начальный предел не должен разрешать третье отражение.")
	TEST_ASSERT_EQUAL(length(knowledge.reflections), 2, "Отказ создания не должен менять список отражений.")
	first.adjustBruteLoss(20)
	TEST_ASSERT(QDELETED(first), "Отражение должно разрушаться обычным уроном.")
	TEST_ASSERT_EQUAL(length(knowledge.reflections), 1, "Разбитое отражение должно освобождать место в списке.")
	knowledge.upgraded = TRUE
	TEST_ASSERT_EQUAL(knowledge.reflection_limit(), 3, "Улучшение должно давать три отражения.")
	knowledge.ascension_active = TRUE
	TEST_ASSERT_EQUAL(knowledge.reflection_limit(), 5, "Вознесение должно давать пять отражений.")
	knowledge.clear_reflections()
	TEST_ASSERT(QDELETED(second), "Очистка должна удалять оставшиеся отражения.")
	TEST_ASSERT_EQUAL(length(knowledge.reflections), 0, "После очистки список должен быть пуст.")

/datum/unit_test/heretic_moon_exchange/Run()
	var/mob/living/user = make_moon_heretic(run_loc_floor_bottom_left)
	var/datum/eldritch_knowledge/base_moon/knowledge = get_heretic_moon(user)
	var/turf/origin = get_turf(user)
	var/turf/destination = get_step(user, EAST)
	var/mob/living/simple_animal/hostile/illusion/heretic_moon/reflection = knowledge.create_reflection(user, destination)
	TEST_ASSERT_NOTNULL(reflection, "Отражение для обмена не создано.")
	var/obj/structure/blocker = allocate(/obj/structure, destination)
	blocker.density = TRUE
	TEST_ASSERT(!knowledge.exchange(user, reflection), "Плотное препятствие должно блокировать обмен.")
	TEST_ASSERT_EQUAL(get_turf(user), origin, "Неудачный обмен не должен перемещать игрока.")
	blocker.forceMove(null)
	qdel(blocker)
	var/obj/container = allocate(/obj, destination)
	reflection.forceMove(container)
	TEST_ASSERT(!knowledge.exchange(user, reflection), "Нельзя обмениваться с двойником внутри контейнера.")
	reflection.forceMove(destination)
	ADD_TRAIT(user, TRAIT_NO_TELEPORT, "moon-test")
	TEST_ASSERT(!knowledge.exchange(user, reflection), "Запрет телепортации должен блокировать обмен.")
	REMOVE_TRAIT(user, TRAIT_NO_TELEPORT, "moon-test")
	TEST_ASSERT(knowledge.exchange(user, reflection), "Свободные соседние клетки должны разрешать обмен.")
	TEST_ASSERT_EQUAL(get_turf(user), destination, "Игрок должен оказаться на месте отражения.")
	TEST_ASSERT_EQUAL(get_turf(reflection), origin, "Отражение должно занять прежнее место игрока.")
	var/mob/living/other_user = make_moon_heretic(get_step(destination, NORTH))
	TEST_ASSERT(!knowledge.exchange(other_user, reflection), "Другой игрок не должен использовать чужое отражение.")
	var/datum/eldritch_knowledge/base_moon/other_knowledge = get_heretic_moon(other_user)
	TEST_ASSERT(!other_knowledge.exchange(other_user, reflection), "Чужое отражение не должно приниматься другим знанием Луны.")

/datum/unit_test/heretic_moon_cleanup/Run()
	var/mob/living/user = make_moon_heretic(run_loc_floor_bottom_left)
	var/datum/eldritch_knowledge/base_moon/knowledge = get_heretic_moon(user)
	var/mob/living/simple_animal/hostile/illusion/heretic_moon/reflection = knowledge.create_reflection(user, get_step(user, EAST))
	var/obj/effect/proc_holder/spell/pointed/heretic_moon/create/granted = knowledge.reflection_spell
	var/obj/effect/proc_holder/spell/pointed/heretic_moon/create/unrelated = allocate(/obj/effect/proc_holder/spell/pointed/heretic_moon/create)
	user.mind.AddSpell(unrelated)
	user.alpha = 150
	user.add_filter("moon-test-independent", 1, list("type" = "outline", "size" = 1, "color" = "#ffffff"))
	var/datum/status_effect/heretic_moon_shroud/shroud = user.apply_status_effect(/datum/status_effect/heretic_moon_shroud)
	TEST_ASSERT_NOTNULL(shroud, "Лунный покров должен применяться.")
	TEST_ASSERT_NOTNULL(user.get_filter(shroud.filter_name), "Покров должен создавать собственный фильтр.")
	var/old_filter_name = shroud.filter_name
	shroud = user.apply_status_effect(/datum/status_effect/heretic_moon_shroud, 1 SECONDS)
	TEST_ASSERT_NULL(user.get_filter(old_filter_name), "Повторное применение покрова должно убирать фильтр предыдущего экземпляра.")
	TEST_ASSERT_NOTNULL(user.get_filter(shroud.filter_name), "Новый экземпляр покрова должен иметь свой фильтр.")
	knowledge.on_body_lose(user)
	TEST_ASSERT(QDELETED(reflection), "При смене тела отражения старого тела должны исчезать.")
	TEST_ASSERT(QDELETED(granted), "Выданное знанием заклинание должно удаляться.")
	TEST_ASSERT(!QDELETED(unrelated), "Другое заклинание того же типа должно сохраняться.")
	TEST_ASSERT_EQUAL(user.alpha, 150, "Снятие покрова не должно переписывать исходную прозрачность.")
	TEST_ASSERT_NOTNULL(user.get_filter("moon-test-independent"), "Снятие покрова не должно удалять чужой фильтр.")
	TEST_ASSERT(!user.has_status_effect(/datum/status_effect/heretic_moon_shroud), "Снятие знаний должно убирать лунный покров.")
	TEST_ASSERT_NULL(knowledge.moon_body, "Ссылка на прежнее тело должна очищаться.")

/datum/unit_test/heretic_moon_expiry/Run()
	var/mob/living/user = make_moon_heretic(run_loc_floor_bottom_left)
	var/datum/eldritch_knowledge/base_moon/knowledge = get_heretic_moon(user)
	var/mob/living/simple_animal/hostile/illusion/heretic_moon/reflection = allocate(/mob/living/simple_animal/hostile/illusion/heretic_moon, get_step(user, EAST), knowledge, user, 1)
	knowledge.reflections += reflection
	TEST_ASSERT(wait_for_qdeleted(reflection), "Отражение должно исчезать по истечении своего времени жизни.")
	TEST_ASSERT_EQUAL(length(knowledge.reflections), 0, "Истёкшее отражение должно освобождать место для нового.")

/datum/unit_test/heretic_moon_reveal/Run()
	var/mob/living/user = make_moon_heretic(run_loc_floor_bottom_left)
	var/mob/living/other = allocate(/mob/living/carbon/human, get_step(user, EAST))
	var/datum/status_effect/heretic_moon_shroud/shroud = user.apply_status_effect(/datum/status_effect/heretic_moon_shroud)
	var/filter_name = shroud.filter_name
	user.attack_hand(other, INTENT_HELP)
	TEST_ASSERT(user.has_status_effect(/datum/status_effect/heretic_moon_shroud), "Чужое дружеское касание не должно считаться атакой владельца покрова.")
	user.UnarmedAttack(other, TRUE, INTENT_HARM)
	TEST_ASSERT(!user.has_status_effect(/datum/status_effect/heretic_moon_shroud), "Исходящий удар без оружия должен раскрывать владельца покрова.")
	TEST_ASSERT_NULL(user.get_filter(filter_name), "Раскрытие атакой должно удалять фильтр прозрачности.")

/datum/unit_test/heretic_moon_allies/Run()
	var/mob/living/user = make_moon_heretic(run_loc_floor_bottom_left)
	var/mob/living/ally = make_moon_heretic(get_step(user, NORTH))
	var/mob/living/victim = allocate(/mob/living/carbon/human, get_step(user, EAST))
	var/datum/eldritch_knowledge/moon_mark/mark = allocate(/datum/eldritch_knowledge/moon_mark)
	TEST_ASSERT(!mark.on_mansus_grasp(ally, user, TRUE), "Метка Луны не должна действовать на другого еретика.")
	TEST_ASSERT(mark.on_mansus_grasp(victim, user, TRUE), "Метка Луны должна действовать на обычного противника.")
	var/datum/status_effect/eldritch/moon/effect = victim.has_status_effect(/datum/status_effect/eldritch/moon)
	TEST_ASSERT_NOTNULL(effect, "Хватка должна оставить лунную метку.")
	effect.on_effect()
	TEST_ASSERT(victim.confused > 0, "Активация метки должна дезориентировать жертву.")
	TEST_ASSERT_EQUAL(victim.getStaminaLoss(), 20, "Активация метки должна наносить урон выносливости.")
	TEST_ASSERT(victim.has_status_effect(/datum/status_effect/heretic_moon_opening), "Метка должна замедлять цель для атаки двойников.")
	TEST_ASSERT(!victim.has_status_effect(/datum/status_effect/eldritch/moon), "Активированная метка должна расходоваться.")

/// Лунный клинок наносит обычный урон и разбивает отражение одним попаданием.
/datum/unit_test/heretic_moon_blade_damage/Run()
	var/mob/living/user = make_moon_heretic(run_loc_floor_bottom_left)
	var/datum/eldritch_knowledge/base_moon/knowledge = get_heretic_moon(user)
	var/obj/item/melee/sickly_blade/moon/blade = allocate(/obj/item/melee/sickly_blade/moon)
	user.put_in_hands(blade)
	user.a_intent = INTENT_HARM
	var/mob/living/simple_animal/hostile/illusion/heretic_moon/reflection = knowledge.create_reflection(user, get_step(user, EAST))
	TEST_ASSERT_NOTNULL(reflection, "Отражение для проверки удара должно создаться.")
	blade.attack(reflection, user)
	TEST_ASSERT(QDELETED(reflection), "Одно попадание лунным клинком разбивает отражение.")
	var/mob/living/victim = allocate(/mob/living/carbon/human, get_step(user, EAST))
	blade.attack(victim, user)
	TEST_ASSERT(victim.getBruteLoss() > 0, "Лунный путь сохраняет обычный урон своего клинка.")

/// Ручное зеркало перемещает именно копию, сохраняя общий лимит и уязвимость к разрушению.
/datum/unit_test/heretic_moon_hand_mirror/Run()
	var/mob/living/user = make_moon_heretic(run_loc_floor_bottom_left)
	var/datum/antagonist/heretic/heretic = IS_HERETIC(user)
	var/datum/eldritch_knowledge/base_moon/knowledge = get_heretic_moon(user)
	var/datum/eldritch_knowledge/moon_shroud/recipe = allocate(/datum/eldritch_knowledge/moon_shroud)
	heretic.researched_knowledge[recipe.type] = recipe
	TEST_ASSERT(recipe.on_finished_recipe(user, list(), get_turf(user)), "Ритуал должен создать серебряное зеркало.")
	var/obj/item/heretic_path_relic/silver_mirror/mirror = recipe.new_path_relic_ref.resolve()
	allocated += mirror
	user.put_in_hands(mirror)
	mirror.focusing_time = 0
	var/turf/origin = get_turf(user)
	var/turf/destination = get_step(origin, NORTH)
	var/mob/living/simple_animal/hostile/illusion/heretic_moon/reflection = knowledge.create_reflection(user, get_step(origin, EAST))
	var/original_expiry = reflection.reflection_expires_at
	mirror.selected_reflection = WEAKREF(reflection)
	var/obj/container = allocate(/obj, get_turf(reflection))
	reflection.forceMove(container)
	TEST_ASSERT(!mirror.redirect(user, destination), "Зеркало не должно вытаскивать двойника из контейнера.")
	reflection.forceMove(get_turf(container))
	var/obj/barrier = allocate(/obj, destination)
	barrier.density = TRUE
	TEST_ASSERT(!mirror.redirect(user, destination), "Зеркало не переносит отражение в плотное препятствие.")
	qdel(barrier)
	TEST_ASSERT(mirror.redirect(user, destination), "Свободная видимая клетка позволяет переставить копию.")
	TEST_ASSERT_EQUAL(get_turf(user), origin, "Ручное зеркало не телепортирует самого владельца.")
	TEST_ASSERT_EQUAL(get_turf(reflection), destination, "Существующая копия занимает выбранную клетку.")
	TEST_ASSERT_EQUAL(reflection.reflection_expires_at, original_expiry, "Перестановка не продлевает жизнь отражения.")
	TEST_ASSERT_EQUAL(length(knowledge.reflections), 1, "Перестановка не размножает отражения.")
	TEST_ASSERT(!mirror.redirect(user, get_step(origin, EAST)), "Сразу после перестановки действует перезарядка.")
	mirror.relic_cooldown = 0
	qdel(reflection)
	TEST_ASSERT(!mirror.redirect(user, get_step(origin, EAST)), "Разрушенное отражение нельзя восстановить перестановкой.")
	qdel(recipe)
	TEST_ASSERT(!mirror.authorized(user), "Потеря знания делает уже созданное зеркало неактивным.")

/// Двойник сохраняет облик и экипировку владельца, но не копирует лунный покров.
/datum/unit_test/heretic_moon_appearance/Run()
	var/mob/living/carbon/human/user = make_moon_heretic(run_loc_floor_bottom_left)
	var/datum/eldritch_knowledge/base_moon/knowledge = get_heretic_moon(user)
	user.alpha = 210
	user.transform = matrix(1.2, 0, 0, 0, 1.2, 0)
	user.add_filter("moon-test-outline", 1, outline_filter(1, "#ff0000"))
	var/obj/item/clothing/head/helmet/helmet = allocate(/obj/item/clothing/head/helmet)
	user.equip_to_slot_if_possible(helmet, ITEM_SLOT_HEAD)
	var/mob/living/simple_animal/hostile/illusion/heretic_moon/reflection = knowledge.create_reflection(user, get_step(user, EAST))
	TEST_ASSERT_NOTNULL(reflection, "Двойник должен создаться.")
	TEST_ASSERT_EQUAL(reflection.name, user.name, "Имя не должно выдавать копию.")
	TEST_ASSERT_EQUAL(reflection.icon, user.icon, "Базовая иконка должна совпадать.")
	TEST_ASSERT_EQUAL(reflection.alpha, user.alpha, "Двойник не должен получать собственную прозрачность.")
	TEST_ASSERT_EQUAL(reflection.transform.a, user.transform.a, "Масштаб персонажа должен сохраняться.")
	TEST_ASSERT_EQUAL(length(reflection.overlays), length(user.overlays), "Все слои экипировки должны копироваться без лунных колец.")
	TEST_ASSERT_EQUAL(length(reflection.filters), length(user.filters), "Двойник не должен получать дополнительную обводку.")
	TEST_ASSERT_EQUAL(jointext(reflection.examine(user), "\n"), jointext(user.examine(user), "\n"), "Осмотр должен показывать тот же облик, а не описание подделки.")
	user.dropItemToGround(helmet)
	user.apply_status_effect(/datum/status_effect/heretic_moon_shroud)
	reflection.sync_appearance()
	TEST_ASSERT_EQUAL(length(reflection.overlays), length(user.overlays), "Изменение экипировки должно обновлять двойника.")
	TEST_ASSERT_EQUAL(length(reflection.filters), 1, "Копия сохраняет исходный фильтр без лунного покрова.")
	TEST_ASSERT_EQUAL(length(user.filters), 2, "Синхронизация копии не должна изменять фильтры владельца.")

/// Двойники получают цель в контроллере и делят ограничение урона выносливости.
/datum/unit_test/heretic_moon_pressure/Run()
	var/mob/living/user = make_moon_heretic(run_loc_floor_bottom_left)
	var/datum/eldritch_knowledge/base_moon/knowledge = get_heretic_moon(user)
	var/mob/living/simple_animal/hostile/illusion/heretic_moon/first = knowledge.create_reflection(user, get_step(user, EAST))
	var/mob/living/simple_animal/hostile/illusion/heretic_moon/second = knowledge.create_reflection(user, get_step(user, NORTH))
	var/mob/living/victim = allocate(/mob/living/carbon/human, get_step(user, NORTHEAST))
	knowledge.direct_reflections(victim)
	TEST_ASSERT_NOTNULL(first.ai_controller, "У двойника должен быть контроллер движения и атак.")
	TEST_ASSERT_EQUAL(first.ai_controller.blackboard[BB_AI_CURRENT_TARGET], victim, "Команда должна передавать цель контроллеру.")
	TEST_ASSERT(first.AttackingTarget(), "Соседняя цель должна принимать ложный удар.")
	TEST_ASSERT_EQUAL(victim.getBruteLoss(), 0, "Ложный удар не должен наносить ранения.")
	TEST_ASSERT_EQUAL(victim.getStaminaLoss(), 8, "Начальное отражение наносит 8 урона выносливости.")
	second.AttackingTarget()
	TEST_ASSERT_EQUAL(victim.getStaminaLoss(), 8, "Вторая копия не должна обходить общий интервал.")
	victim.remove_status_effect(/datum/status_effect/heretic_moon_pressure)
	knowledge.upgraded = TRUE
	second.AttackingTarget()
	TEST_ASSERT_EQUAL(victim.getStaminaLoss(), 20, "Улучшение увеличивает ложный удар до 12.")
	victim.remove_status_effect(/datum/status_effect/heretic_moon_pressure)
	knowledge.ascension_active = TRUE
	first.AttackingTarget()
	TEST_ASSERT_EQUAL(victim.getStaminaLoss(), 40, "Вознесение увеличивает ложный удар до 20.")
	TEST_ASSERT(!first.CanAttack(user), "Двойник не должен атаковать владельца.")
	TEST_ASSERT(!first.CanAttack(second), "Двойники не должны атаковать друг друга.")
	var/mob/living/ally = make_moon_heretic(get_step(victim, NORTH))
	TEST_ASSERT(!first.CanAttack(ally), "Другой еретик должен оставаться союзником.")
	var/obj/structure/closet/closet = allocate(/obj/structure/closet, get_turf(victim))
	victim.forceMove(closet)
	TEST_ASSERT(!first.AttackingTarget(), "Ложный удар не должен доставать цель внутри шкафа.")

/// Шествие заменяет полный набор отражений и оставляет двойника на прежнем месте владельца.
/datum/unit_test/heretic_moon_mirage/Run()
	var/mob/living/user = make_moon_heretic(run_loc_floor_bottom_left)
	var/datum/eldritch_knowledge/base_moon/knowledge = get_heretic_moon(user)
	knowledge.upgraded = TRUE
	var/mob/living/simple_animal/hostile/illusion/heretic_moon/old = knowledge.create_reflection(user, get_step(user, EAST))
	knowledge.create_reflection(user, get_step(user, NORTH))
	knowledge.create_reflection(user, get_step(user, NORTHEAST))
	var/turf/origin = get_turf(user)
	TEST_ASSERT(knowledge.create_mirages(user), "Шествие должно работать при полном наборе отражений.")
	TEST_ASSERT(QDELETED(old), "Старые отражения должны заменяться.")
	TEST_ASSERT_EQUAL(length(knowledge.reflections), 3, "Шествие должно использовать улучшенный предел.")
	TEST_ASSERT_NOTEQUAL(get_turf(user), origin, "Шествие должно менять позицию владельца.")
	TEST_ASSERT(locate(/mob/living/simple_animal/hostile/illusion/heretic_moon) in origin, "На прежнем месте должна оставаться копия.")
	ADD_TRAIT(user, TRAIT_NO_TELEPORT, "moon-test")
	origin = get_turf(user)
	TEST_ASSERT(knowledge.create_mirages(user), "Запрет телепортации не должен запрещать создание двойников.")
	TEST_ASSERT_EQUAL(get_turf(user), origin, "Шествие должно соблюдать запрет телепортации.")
	REMOVE_TRAIT(user, TRAIT_NO_TELEPORT, "moon-test")

/// Вспышка разбитой копии действует на врага, но не срабатывает при обычной очистке.
/datum/unit_test/heretic_moon_refraction/Run()
	var/mob/living/user = make_moon_heretic(run_loc_floor_bottom_left)
	var/datum/eldritch_knowledge/base_moon/knowledge = get_heretic_moon(user)
	knowledge.refracting = TRUE
	var/mob/living/simple_animal/hostile/illusion/heretic_moon/reflection = knowledge.create_reflection(user, get_step(user, EAST))
	var/mob/living/victim = allocate(/mob/living/carbon/human, get_step(user, NORTHEAST))
	reflection.adjustBruteLoss(20)
	TEST_ASSERT(QDELETED(reflection), "Урон должен разбивать копию.")
	TEST_ASSERT_EQUAL(victim.getStaminaLoss(), 15, "Разбитая копия должна изматывать ближайшего врага.")
	TEST_ASSERT_EQUAL(user.getStaminaLoss(), 0, "Вспышка не должна изматывать владельца.")
	victim.remove_status_effect(/datum/status_effect/heretic_moon_pressure)
	knowledge.create_reflection(user, get_step(user, EAST))
	knowledge.clear_reflections()
	TEST_ASSERT_EQUAL(victim.getStaminaLoss(), 15, "Очистка не должна наносить урон вспышкой.")

/// Затмение действует вокруг двойников и оставляет видимую копию под покровом владельца.
/datum/unit_test/heretic_moon_eclipse/Run()
	var/mob/living/user = make_moon_heretic(run_loc_floor_bottom_left)
	var/datum/eldritch_knowledge/base_moon/knowledge = get_heretic_moon(user)
	var/turf/far_turf = get_step(get_step(get_step(user, EAST), EAST), EAST)
	var/mob/living/simple_animal/hostile/illusion/heretic_moon/reflection = knowledge.create_reflection(user, far_turf)
	TEST_ASSERT_NOTNULL(reflection, "Удалённое отражение должно создаться.")
	var/mob/living/victim = allocate(/mob/living/carbon/human, get_step(far_turf, NORTH))
	var/obj/effect/proc_holder/spell/self/heretic_moon/eclipse/spell = allocate(/obj/effect/proc_holder/spell/self/heretic_moon/eclipse)
	spell.cast(list(user), user)
	TEST_ASSERT(victim.confused > 0, "Вспышка двойника должна доставать врага дальше двух клеток от владельца.")
	var/datum/status_effect/heretic_moon_shroud/shroud = user.has_status_effect(/datum/status_effect/heretic_moon_shroud)
	TEST_ASSERT_NOTNULL(shroud, "Затмение должно скрывать владельца.")
	var/mob/living/simple_animal/hostile/illusion/heretic_moon/decoy = locate() in get_turf(user)
	TEST_ASSERT_NOTNULL(decoy, "На месте владельца должен появиться двойник.")
	decoy.sync_appearance()
	TEST_ASSERT_EQUAL(length(decoy.filters), length(user.filters) - 1, "Оставленный двойник не должен исчезать вместе с владельцем.")

/// Контроллер самостоятельно подводит двойника к врагу и наносит ложный удар.
/datum/unit_test/heretic_moon_pursuit
	var/mob/living/carbon/human/caster

/datum/unit_test/heretic_moon_pursuit/Run()
	caster = make_moon_heretic(run_loc_floor_bottom_left)
	caster.put_in_hands(allocate(/obj/item/melee/sickly_blade/moon))
	register_fake_player(caster, get_turf(caster))
	var/datum/eldritch_knowledge/base_moon/knowledge = get_heretic_moon(caster)
	var/mob/living/simple_animal/hostile/illusion/heretic_moon/reflection = knowledge.create_reflection(caster, get_step(caster, NORTH))
	var/turf/destination = locate(caster.x + 3, caster.y + 1, caster.z)
	var/mob/living/victim = allocate(/mob/living/carbon/human, destination)
	var/turf/origin = get_turf(reflection)
	var/list/budget = new_wait_budget(10 SECONDS, "двойник должен подойти и атаковать")
	while(!victim.getStaminaLoss())
		if(!wait_budget_tick(budget))
			break
	TEST_ASSERT_NOTEQUAL(get_turf(reflection), origin, "Двойник должен самостоятельно двигаться к врагу.")
	TEST_ASSERT(victim.getStaminaLoss() > 0, "Контроллер должен проводить ложные атаки.")
	TEST_ASSERT_EQUAL(victim.getBruteLoss(), 0, "Автономные атаки не должны наносить ранения.")
	var/obj/item/projectile/bullet = allocate(/obj/item/projectile, destination)
	bullet.damage = 20
	bullet.firer = victim
	bullet.starting = destination
	reflection.bullet_act(bullet)
	TEST_ASSERT(QDELETED(reflection), "Попадание снаряда должно разбивать двойника.")

/datum/unit_test/heretic_moon_pursuit/Destroy()
	if(caster)
		unregister_fake_player(caster)
	caster = null
	return ..()
