/// Печати расходуют ключи только при успешной установке и имеют общий предел.
/datum/unit_test/heretic_lock_seals/Run()
	var/datum/antagonist/heretic/heretic = allocate_heretic()
	var/mob/living/user = heretic.owner.current
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_lock)
	var/datum/eldritch_knowledge/base_lock/knowledge = heretic.get_knowledge(/datum/eldritch_knowledge/base_lock)
	var/turf/first_place = get_step(user, EAST)
	var/obj/structure/heretic_lock_seal/first = knowledge.create_seal(first_place, user)
	TEST_ASSERT_NOTNULL(first, "Свободный пол принимает печать.")
	TEST_ASSERT_EQUAL(knowledge.combat_resource, 1, "Успешная печать стоит один ключ.")
	TEST_ASSERT_EQUAL(first.max_integrity, 60, "Начальная печать имеет 60 прочности.")
	TEST_ASSERT_NULL(knowledge.create_seal(first_place, user), "На одну клетку нельзя поставить две печати.")
	TEST_ASSERT_EQUAL(knowledge.combat_resource, 1, "Отклонённая установка не расходует ключ.")
	TEST_ASSERT_NULL(knowledge.create_seal(get_turf(user), user), "Нельзя создать печать на занятой мобом клетке.")
	var/obj/structure/heretic_lock_seal/second = knowledge.create_seal(get_step(user, NORTH), user)
	TEST_ASSERT_NOTNULL(second, "Второй ключ создаёт вторую печать.")
	TEST_ASSERT_NULL(knowledge.create_seal(get_step(user, NORTHEAST), user), "Пустой запас не создаёт печать.")
	knowledge.gain_combat_resource(10)
	TEST_ASSERT_EQUAL(knowledge.combat_resource, 4, "Ключи не переполняют запас.")
	knowledge.create_seal(get_step(user, NORTHEAST), user)
	knowledge.create_seal(get_step(first_place, EAST), user)
	TEST_ASSERT_EQUAL(length(knowledge.seals), 4, "Начальный предел равен четырём печатям.")
	TEST_ASSERT_NULL(knowledge.create_seal(get_step(get_step(user, NORTH), NORTH), user), "Лимит не обходится оставшимися ключами.")
	first.take_damage(100, BRUTE, MELEE)
	TEST_ASSERT(QDELETED(first), "Обычный урон разрушает печать.")
	TEST_ASSERT_EQUAL(length(knowledge.seals), 3, "Разрушение освобождает место в общем пределе.")

/// Союзники и антимагия проходят через печать, проверка прохода не тратит заряды защиты.
/datum/unit_test/heretic_lock_passage/Run()
	var/datum/antagonist/heretic/heretic = allocate_heretic()
	var/mob/living/user = heretic.owner.current
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_lock)
	var/datum/eldritch_knowledge/base_lock/knowledge = heretic.get_knowledge(/datum/eldritch_knowledge/base_lock)
	var/turf/destination = get_step(user, EAST)
	var/obj/structure/heretic_lock_seal/seal = knowledge.create_seal(destination, user)
	var/mob/living/victim = allocate(/mob/living/carbon/human, get_step(destination, NORTH))
	TEST_ASSERT(seal.CanPass(user, destination), "Хозяин свободно проходит через печать.")
	TEST_ASSERT(!seal.CanPass(victim, destination), "Печать удерживает обычного противника.")
	TEST_ASSERT(!victim.Move(destination, SOUTH), "Настоящее движение не проходит сквозь печать.")
	var/datum/antagonist/heretic/ally = allocate_heretic(get_step(user, NORTH))
	TEST_ASSERT(seal.CanPass(ally.owner.current, destination), "Другой еретик тоже проходит через печать.")
	var/datum/component/anti_magic/protection = victim.AddComponent(/datum/component/anti_magic, TRUE, FALSE, FALSE, null, 5)
	TEST_ASSERT(seal.CanPass(victim, destination), "Защита от магии открывает проход.")
	TEST_ASSERT(seal.CanPass(victim, destination), "Повторная проверка прохода остаётся безопасной.")
	TEST_ASSERT_EQUAL(protection.charges, 5, "Проход не расходует заряды антимагии.")
	TEST_ASSERT(victim.Move(destination, SOUTH), "Защищённый противник действительно проходит через печать.")
	var/obj/item/nullrod/rod = allocate(/obj/item/nullrod)
	seal.attackby(rod, victim)
	TEST_ASSERT(QDELETED(seal), "Нуль-жезл сразу разрушает печать.")

/// Хватка отпирает реальные шлюзы и шкафы, сохраняя сварку и общий интервал добычи ключей.
/datum/unit_test/heretic_lock_opening/Run()
	var/datum/antagonist/heretic/heretic = allocate_heretic()
	var/mob/living/user = heretic.owner.current
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_lock)
	heretic.gain_knowledge(/datum/eldritch_knowledge/lock_grasp)
	var/datum/eldritch_knowledge/base_lock/knowledge = heretic.get_knowledge(/datum/eldritch_knowledge/base_lock)
	var/datum/eldritch_knowledge/lock_grasp/grasp = heretic.get_knowledge(/datum/eldritch_knowledge/lock_grasp)
	knowledge.combat_resource = 0
	var/obj/machinery/door/airlock/door = allocate(/obj/machinery/door/airlock, get_step(user, EAST))
	door.locked = TRUE
	door.welded = TRUE
	TEST_ASSERT(!grasp.on_mansus_grasp(door, user, TRUE), "Сварка не позволяет открыть шлюз.")
	TEST_ASSERT(door.locked, "Неудачная хватка не поднимает болты.")
	TEST_ASSERT_EQUAL(knowledge.combat_resource, 0, "Неудача не создаёт ключ.")
	door.welded = FALSE
	TEST_ASSERT(grasp.on_mansus_grasp(door, user, TRUE), "Хватка открывает запертый шлюз.")
	TEST_ASSERT(!door.locked && !door.density, "Болты подняты, шлюз действительно открыт.")
	TEST_ASSERT_EQUAL(knowledge.combat_resource, 1, "Успешное открытие даёт ключ.")
	TEST_ASSERT(!grasp.on_mansus_grasp(door, user, TRUE), "Открытый шлюз нельзя использовать повторно.")
	var/obj/structure/closet/closet = allocate(/obj/structure/closet, get_step(user, NORTH))
	closet.locked = TRUE
	TEST_ASSERT(grasp.on_mansus_grasp(closet, user, TRUE), "Хватка открывает запертый шкаф.")
	TEST_ASSERT(closet.opened && !closet.locked, "Шкаф открыт, а его замок снят.")
	TEST_ASSERT_EQUAL(knowledge.combat_resource, 1, "Второй замок не обходит общий интервал добычи.")

/// Направленный удар проверяет препятствия, союзников и один раз расходует антимагию при попадании.
/datum/unit_test/heretic_lock_bolt/Run()
	var/datum/antagonist/heretic/heretic = allocate_heretic()
	var/mob/living/user = heretic.owner.current
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_lock)
	var/obj/effect/proc_holder/spell/pointed/heretic_lock/bolt/spell = allocate(/obj/effect/proc_holder/spell/pointed/heretic_lock/bolt)
	var/turf/middle = get_step(user, EAST)
	var/mob/living/victim = allocate(/mob/living/carbon/human, get_step(middle, EAST))
	var/obj/structure/blocker = allocate(/obj/structure, middle)
	blocker.density = TRUE
	TEST_ASSERT(!spell.can_target(victim, user, TRUE), "Даже прозрачное плотное препятствие блокирует удар.")
	spell.charge_counter = 0
	spell.cast(list(victim), user)
	TEST_ASSERT_EQUAL(spell.charge_counter, spell.charge_max, "Невозможный выстрел возвращает заряд.")
	TEST_ASSERT_EQUAL(victim.getFireLoss(), 0, "Сквозь препятствие нет урона.")
	qdel(blocker)
	var/datum/antagonist/heretic/ally = allocate_heretic(get_step(user, NORTH))
	TEST_ASSERT(!spell.can_target(ally.owner.current, user, TRUE), "Союзник не становится целью заклинания.")
	var/datum/component/anti_magic/protection = victim.AddComponent(/datum/component/anti_magic, TRUE, FALSE, FALSE, null, 5)
	TEST_ASSERT(spell.can_target(victim, user, TRUE), "Видимого противника можно выбрать без расхода защиты.")
	TEST_ASSERT_EQUAL(protection.charges, 5, "Прицеливание не расходует защиту.")
	spell.cast(list(victim), user)
	TEST_ASSERT_EQUAL(protection.charges, 4, "Попадание расходует ровно один заряд антимагии.")
	TEST_ASSERT_EQUAL(victim.getFireLoss(), 0, "Антимагия блокирует ожоги.")
	qdel(protection)
	spell.cast(list(victim), user)
	TEST_ASSERT(abs(victim.getFireLoss() - 15) < 0.001, "Незащищённая цель получает 15 ожогов.")
	TEST_ASSERT(abs(victim.getStaminaLoss() - 15) < 0.001, "Незащищённая цель получает 15 урона выносливости.")

/// Клинок активирует свою метку, добывает ключ и закрывает свободный проход позади противника.
/datum/unit_test/heretic_lock_mark/Run()
	var/datum/antagonist/heretic/heretic = allocate_heretic()
	var/mob/living/user = heretic.owner.current
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_lock)
	heretic.gain_knowledge(/datum/eldritch_knowledge/lock_mark)
	var/datum/eldritch_knowledge/base_lock/knowledge = heretic.get_knowledge(/datum/eldritch_knowledge/base_lock)
	var/datum/eldritch_knowledge/lock_mark/mark_knowledge = heretic.get_knowledge(/datum/eldritch_knowledge/lock_mark)
	var/mob/living/victim = allocate(/mob/living/carbon/human, get_step(user, EAST))
	TEST_ASSERT(mark_knowledge.on_mansus_grasp(victim, user, TRUE), "Хватка накладывает метку Замка.")
	TEST_ASSERT_EQUAL(length(knowledge.marks), 1, "Знание отслеживает метку для очистки.")
	var/obj/item/melee/sickly_blade/lock/blade = allocate(/obj/item/melee/sickly_blade/lock)
	user.put_in_hands(blade)
	user.a_intent = INTENT_HARM
	blade.attack(victim, user)
	TEST_ASSERT(!victim.has_status_effect(/datum/status_effect/eldritch/lock), "Удар расходует метку.")
	TEST_ASSERT_EQUAL(length(knowledge.marks), 0, "Сработавшая метка больше не удерживается знанием.")
	TEST_ASSERT(abs(victim.getStaminaLoss() - 15) < 0.001, "Активация наносит 15 урона выносливости.")
	TEST_ASSERT_EQUAL(knowledge.combat_resource, 3, "Активация возвращает один ключ.")
	TEST_ASSERT_EQUAL(length(knowledge.seals), 1, "За спиной появляется одна бесплатная печать.")
	var/obj/structure/heretic_lock_seal/seal = knowledge.seals[1]
	TEST_ASSERT_EQUAL(get_turf(seal), get_step(victim, EAST), "Печать появляется на стороне отступления от еретика.")
	TEST_ASSERT(seal.expires_at <= world.time + 8 SECONDS, "Метка создаёт короткую восьмисекундную печать.")
	heretic.gain_knowledge(/datum/eldritch_knowledge/lock_blade_upgrade)
	var/datum/eldritch_knowledge/lock_blade_upgrade/upgrade = heretic.get_knowledge(/datum/eldritch_knowledge/lock_blade_upgrade)
	var/damage_before = victim.getBruteLoss()
	upgrade.on_eldritch_blade(victim, user, TRUE)
	TEST_ASSERT(abs(victim.getBruteLoss() - (damage_before + 5)) < 0.001, "Своя печать усиливает клинок на 5 ушибов.")

/// Размыкание рядом с несколькими печатями не складывает урон и заряды антимагии.
/datum/unit_test/heretic_lock_release/Run()
	var/datum/antagonist/heretic/heretic = allocate_heretic()
	var/mob/living/user = heretic.owner.current
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_lock)
	var/datum/eldritch_knowledge/base_lock/knowledge = heretic.get_knowledge(/datum/eldritch_knowledge/base_lock)
	knowledge.create_seal(get_step(user, EAST), user)
	knowledge.create_seal(get_step(user, NORTH), user)
	var/turf/target_turf = get_step(user, NORTHEAST)
	var/mob/living/victim = allocate(/mob/living/carbon/human, target_turf)
	var/mob/living/protected = allocate(/mob/living/carbon/human, target_turf)
	var/datum/component/anti_magic/protection = protected.AddComponent(/datum/component/anti_magic, TRUE, FALSE, FALSE, null, 5)
	var/datum/antagonist/heretic/ally = allocate_heretic(target_turf)
	TEST_ASSERT(knowledge.release_seals(user), "Подготовленные печати размыкаются.")
	TEST_ASSERT(abs(victim.getBruteLoss() - 20) < 0.001, "Две соседние печати наносят 20 ушибов один раз.")
	TEST_ASSERT_EQUAL(protected.getBruteLoss(), 0, "Антимагия блокирует размыкание.")
	TEST_ASSERT_EQUAL(protection.charges, 4, "Защита расходуется один раз за всё применение.")
	TEST_ASSERT_EQUAL(ally.owner.current.getBruteLoss(), 0, "Другой еретик защищён от размыкания.")
	TEST_ASSERT_EQUAL(user.getBruteLoss(), 0, "Владелец не получает урон своих печатей.")
	TEST_ASSERT_EQUAL(length(knowledge.seals), 0, "Размыкание расходует все выбранные печати.")
	TEST_ASSERT(!knowledge.release_seals(user), "Без печатей заклинание не срабатывает.")

/// Усиление сохраняет повреждения и срок жизни уже созданных печатей.
/datum/unit_test/heretic_lock_hinges/Run()
	var/datum/antagonist/heretic/heretic = allocate_heretic()
	var/mob/living/user = heretic.owner.current
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_lock)
	var/datum/eldritch_knowledge/base_lock/knowledge = heretic.get_knowledge(/datum/eldritch_knowledge/base_lock)
	var/obj/structure/heretic_lock_seal/seal = knowledge.create_seal(get_step(user, EAST), user)
	seal.take_damage(20, BRUTE, MELEE)
	var/original_expiry = seal.expires_at
	heretic.gain_knowledge(/datum/eldritch_knowledge/lock_hinges)
	TEST_ASSERT_EQUAL(seal.max_integrity, 90, "Изучение усиливает существующую печать.")
	TEST_ASSERT_EQUAL(seal.obj_integrity, 70, "Повреждение в 20 единиц сохраняется.")
	TEST_ASSERT_EQUAL(knowledge.seal_limit(), 10, "Изучение увеличивает общий предел до десяти.")
	var/datum/eldritch_knowledge/lock_hinges/hinges = heretic.get_knowledge(/datum/eldritch_knowledge/lock_hinges)
	hinges.passive_level = 3
	hinges.on_passive_upgrade(user)
	TEST_ASSERT_EQUAL(seal.max_integrity, 120, "Третий уровень даёт 120 прочности.")
	TEST_ASSERT_EQUAL(seal.obj_integrity, 100, "Покупка пассивки сохраняет прежние повреждения.")
	TEST_ASSERT_EQUAL(seal.expires_at, original_expiry, "Усиление не продлевает существование печати.")

/// Двор создаёт только предупреждённые свободные клетки и отклоняет старую подготовку после смерти.
/datum/unit_test/heretic_lock_court/Run()
	var/datum/antagonist/heretic/heretic = allocate_heretic()
	var/mob/living/user = heretic.owner.current
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_lock)
	var/datum/eldritch_knowledge/base_lock/knowledge = heretic.get_knowledge(/datum/eldritch_knowledge/base_lock)
	var/turf/center = get_step(get_step(user, NORTHEAST), NORTHEAST)
	user.forceMove(center)
	var/list/positions = knowledge.court_turfs(center, user)
	TEST_ASSERT_EQUAL(length(positions), 8, "Открытый двор занимает восемь клеток вокруг центра.")
	TEST_ASSERT(!knowledge.raise_court(user, positions), "Начальный предел не вмещает полный двор.")
	TEST_ASSERT_EQUAL(knowledge.combat_resource, 2, "Нехватка лимита не расходует ключи.")
	heretic.gain_knowledge(/datum/eldritch_knowledge/lock_hinges)
	var/generation = knowledge.court_generation
	knowledge.court_busy = TRUE
	knowledge.on_death(user)
	TEST_ASSERT(!knowledge.court_busy, "Смерть освобождает признак занятого заклинания.")
	TEST_ASSERT(!knowledge.raise_court(user, positions, expected_generation = generation), "Подготовка до смерти не завершается после возвращения в сознание.")
	TEST_ASSERT_EQUAL(knowledge.combat_resource, 2, "Устаревшая подготовка не расходует ключи.")
	var/turf/blocked_place = positions[1]
	var/mob/living/blocker = allocate(/mob/living/carbon/human, blocked_place)
	TEST_ASSERT(knowledge.raise_court(user, positions, expected_generation = knowledge.court_generation), "Оставшиеся свободные места принимают двор.")
	TEST_ASSERT_EQUAL(length(knowledge.seals), 7, "Занятая после предупреждения клетка остаётся свободной от печати.")
	TEST_ASSERT_EQUAL(get_turf(blocker), blocked_place, "Создание двора не выталкивает занятого моба.")
	TEST_ASSERT_EQUAL(knowledge.combat_resource, 0, "Весь двор стоит два ключа.")
	for(var/obj/structure/heretic_lock_seal/seal as anything in knowledge.seals)
		TEST_ASSERT(get_turf(seal) in positions, "Печати появляются только на предупреждённых клетках.")

/// Ритуальный ключ работает при пустом запасе, оплачивается здоровьем и связан с владельцем знания.
/datum/unit_test/heretic_lock_relic/Run()
	var/datum/antagonist/heretic/heretic = allocate_heretic()
	var/mob/living/user = heretic.owner.current
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_lock)
	heretic.gain_knowledge(/datum/eldritch_knowledge/lock_key)
	var/datum/eldritch_knowledge/base_lock/knowledge = heretic.get_knowledge(/datum/eldritch_knowledge/base_lock)
	var/datum/eldritch_knowledge/lock_key/recipe = heretic.get_knowledge(/datum/eldritch_knowledge/lock_key)
	TEST_ASSERT(recipe.on_finished_recipe(user, list(), get_turf(user)), "Обряд создаёт ритуальный ключ.")
	var/obj/item/heretic_path_relic/lock_key/key = recipe.new_path_relic_ref.resolve()
	allocated += key
	user.put_in_hands(key)
	key.cutting_time = 0
	TEST_ASSERT(!recipe.on_finished_recipe(user, list(), get_turf(user)), "Нельзя создать вторую работающую реликвию.")
	TEST_ASSERT(!key.cut_key(user), "Непустой запас не пополняется реликвией.")
	knowledge.combat_resource = 0
	TEST_ASSERT(key.cut_key(user), "При пустом запасе реликвия создаёт ключ.")
	TEST_ASSERT_EQUAL(knowledge.combat_resource, 1, "Реликвия создаёт один ключ.")
	var/paid_damage = user.getBruteLoss()
	TEST_ASSERT(abs(paid_damage - 8) < 0.001, "Реликвия причиняет 8 ушибов.")
	knowledge.combat_resource = 0
	TEST_ASSERT(!key.cut_key(user), "Повторное применение ограничено перезарядкой.")
	TEST_ASSERT_EQUAL(user.getBruteLoss(), paid_damage, "Отказ не причиняет нового урона.")
	qdel(recipe)
	TEST_ASSERT(!key.authorized(user), "Удалённое знание отключает реликвию.")

/// Потеря тела удаляет печати, метки и только собственный экземпляр заклинания.
/datum/unit_test/heretic_lock_cleanup/Run()
	var/datum/antagonist/heretic/heretic = allocate_heretic()
	var/mob/living/user = heretic.owner.current
	heretic.gain_knowledge(/datum/eldritch_knowledge/base_lock)
	heretic.gain_knowledge(/datum/eldritch_knowledge/lock_mark)
	var/datum/eldritch_knowledge/base_lock/knowledge = heretic.get_knowledge(/datum/eldritch_knowledge/base_lock)
	var/datum/eldritch_knowledge/lock_mark/mark_knowledge = heretic.get_knowledge(/datum/eldritch_knowledge/lock_mark)
	var/obj/structure/heretic_lock_seal/seal = knowledge.create_seal(get_step(user, EAST), user)
	var/mob/living/victim = allocate(/mob/living/carbon/human, get_step(user, NORTH))
	mark_knowledge.on_mansus_grasp(victim, user, TRUE)
	var/datum/status_effect/eldritch/lock/mark = victim.has_status_effect(/datum/status_effect/eldritch/lock)
	var/obj/effect/proc_holder/spell/own_spell = knowledge.seal_spell
	var/obj/effect/proc_holder/spell/foreign_spell = allocate(/obj/effect/proc_holder/spell/pointed/heretic_lock/seal)
	heretic.owner.AddSpell(foreign_spell)
	knowledge.on_body_lose(user)
	TEST_ASSERT(QDELETED(seal), "Потеря тела удаляет печать.")
	TEST_ASSERT(QDELETED(mark), "Потеря тела снимает наложенную метку с чужого тела.")
	TEST_ASSERT(QDELETED(own_spell), "Потеря тела удаляет выданное знанием заклинание.")
	TEST_ASSERT(!QDELETED(foreign_spell), "Чужой экземпляр такого же заклинания сохраняется.")
	TEST_ASSERT_NULL(knowledge.lock_body, "Ссылка на старое тело очищается.")
	TEST_ASSERT_EQUAL(length(knowledge.seals) + length(knowledge.marks), 0, "В списках не остаётся старых эффектов.")
	knowledge.on_body_gain(user)
	TEST_ASSERT_NOTNULL(knowledge.seal_spell, "Новое получение тела восстанавливает способность.")
	var/obj/structure/heretic_lock_seal/expiring = knowledge.create_seal(get_step(user, EAST), user, lifetime = 0.1 SECONDS)
	TEST_ASSERT_NOTNULL(expiring, "Короткая печать создана.")
	TEST_ASSERT(wait_for_qdeleted(expiring), "По истечении срока печать удаляется сама.")
	TEST_ASSERT_EQUAL(length(knowledge.seals), 0, "Истечение срока освобождает общий предел.")
