/datum/unit_test/skillchips_implant/Run()
	var/mob/living/carbon/human/H = allocate(/mob/living/carbon/human)
	var/obj/item/skillchip/wine_taster/chip = new /obj/item/skillchip/wine_taster()
	TEST_ASSERT(H.implant_skillchip(chip, force = TRUE), "Имплантация чипа (force) вернула FALSE")
	var/obj/item/organ/brain/brain = H.getorganslot(ORGAN_SLOT_BRAIN)
	TEST_ASSERT_NOTNULL(brain, "Не найден мозг у тестового человека")
	TEST_ASSERT(chip in brain.skillchips, "Чип не оказался в списке скилл-чипов мозга")
	TEST_ASSERT_EQUAL(brain.get_used_skillchip_slots(), 1, "Занято слотов [brain.get_used_skillchip_slots()] вместо 1")
	qdel(chip)

/datum/unit_test/skillchips_activate_deactivate/Run()
	var/mob/living/carbon/human/H = allocate(/mob/living/carbon/human)
	var/obj/item/skillchip/wine_taster/chip = new /obj/item/skillchip/wine_taster()
	H.implant_skillchip(chip, force = TRUE)
	TEST_ASSERT(isnull(chip.try_activate_skillchip(silent = TRUE, force = TRUE)), "Активация чипа вернула ошибку")
	TEST_ASSERT(HAS_TRAIT(H, TRAIT_WINE_TASTER), "Трейт винного дегустатора не выдан")
	var/obj/item/organ/brain/brain = H.getorganslot(ORGAN_SLOT_BRAIN)
	TEST_ASSERT_EQUAL(brain.get_used_skillchip_complexity(), 1, "Сложность не учтена")
	chip.try_deactivate_skillchip(silent = TRUE, force = TRUE)
	TEST_ASSERT(!HAS_TRAIT(H, TRAIT_WINE_TASTER), "Трейт не снят после деактивации")
	TEST_ASSERT_EQUAL(brain.get_used_skillchip_complexity(), 0, "Сложность не обнулена")
	qdel(chip)

/datum/unit_test/skillchips_remove/Run()
	var/mob/living/carbon/human/H = allocate(/mob/living/carbon/human)
	var/obj/item/skillchip/wine_taster/chip = new /obj/item/skillchip/wine_taster()
	H.implant_skillchip(chip, force = TRUE)
	TEST_ASSERT(H.remove_skillchip(chip), "Снятие чипа вернуло FALSE")
	var/obj/item/organ/brain/brain = H.getorganslot(ORGAN_SLOT_BRAIN)
	TEST_ASSERT(!(chip in brain.skillchips), "Чип остался в списке мозга после снятия")
	qdel(chip)

/datum/unit_test/skillchips_brain_removal_failsafe/Run()
	var/mob/living/carbon/human/H = allocate(/mob/living/carbon/human)
	var/obj/item/skillchip/wine_taster/chip = new /obj/item/skillchip/wine_taster()
	H.implant_skillchip(chip, force = TRUE)
	chip.try_activate_skillchip(silent = TRUE, force = TRUE)
	TEST_ASSERT(chip.is_active(), "Чип не активирован")
	var/obj/item/organ/brain/brain = H.getorganslot(ORGAN_SLOT_BRAIN)
	brain.Remove(FALSE)
	TEST_ASSERT(!chip.is_active(), "Чип не деактивирован при извлечении мозга")
	qdel(brain)
	qdel(chip)
